package rss.feeds.subscriber;
import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlRootElement;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

/**
 *  Channel table:
ChannelId
UserId
ChannelName
Set<URL>
 */

@XmlRootElement
@DynamoDBTable(tableName = "channel")
public class ChannelObjectMapper {

	private String id;
	private String userId;
	Set<String> urlSet = new HashSet<String>();
	//List<String> mMatchingKeywords = new ArrayList<String>();
	//Frequency mFrequency;
	String topic;
	
	// TODO: Necessary to provide a default constructor. Need to investigate
	public ChannelObjectMapper() {
		urlSet = new HashSet<String>();
	}
	
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}
	
	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBAttribute
	public String getUserId() {
		return userId;
	}
	
	public void setUserId(String userId) {
		this.userId = userId;
	}
	
	@DynamoDBAttribute
	public String getTopic() {
		return topic;
	}
	
	public void setTopic(String topic) {
		this.topic = topic;
	}
	
	@DynamoDBAttribute
	public Set<String> getUrlSet() {
		return urlSet;
	}
	
	public void setUrlSet(Set<String> urlSet) {
		this.urlSet = urlSet;
	}
	
	/*public Frequency getFrequency() {
		return mFrequency;
	}	
	
	public List<String> getMatchingKeywords() {
		return mMatchingKeywords;
	}*/
		
	/*public void subscribe(List<String> matchingKeywords, Frequency frequency) {
	   mMatchingKeywords.addAll(matchingKeywords);	
	   mFrequency = frequency;	   
	}
	
	public void unsubscribe(List<String> matchingKeywords){
		mMatchingKeywords.removeAll(matchingKeywords);		
	}
	
	public void changeFreqency(Frequency frequency){
		mFrequency = frequency;
	}
	
	public void addFeedURLS(List<String> urlList){
		mURLList.addAll(urlList);
	}*/
}