package rss.feeds.subscriber;

import java.util.LinkedHashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlRootElement;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@XmlRootElement
@DynamoDBTable(tableName = "subscriber")
public class Subscriber {
	
	int mSubscriberId;
	String mEmailAddress;
	String mName;
	Set<Channel> mChannels;
	
	// TODO: creating a default constructor else it cannot be returned by the REST service.
	public Subscriber() {
		mChannels = new LinkedHashSet<Channel>();
	}
	
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	public int getSubscriberId(){
		return mSubscriberId;
	}

	public void setSubscriberId(int subscriberId) {
		mSubscriberId = subscriberId;
	}
	
	@DynamoDBAttribute
	public String getEmailAddress() {
		return mEmailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		mEmailAddress = emailAddress;
	}
	
	@DynamoDBAttribute
	public String getName() {
		return mName;
	}
	
	public void setName(String name) {
		mName = name;
	}
	
	@DynamoDBAttribute
	public Set<Channel> getChannels() {
		return mChannels;
	}

	public void setChannels(Set<Channel> channels) {
		mChannels.addAll(channels);
	}	
}