package rss.feeds.subscriber.dataprovider;
import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlRootElement;

import org.springframework.context.annotation.Configuration;
import org.springframework.stereotype.Component;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

/**
 *  Channel table:
ChannelId
UserId
ChannelName
Set<URL>
 */

@XmlRootElement
@DynamoDBTable(tableName = "channel")
@Configuration
public class ChannelObjectMapper {

	private String id;
	private String subscriberId;
	Set<String> urlSet = new HashSet<String>();
	String topic;

	public ChannelObjectMapper() {
		urlSet = new HashSet<String>();
	}
	
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}
	
	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBAttribute
	public String getSubscriberId() {
		return subscriberId;
	}
	
	public void setSubscriberId(String subscriberId) {
		this.subscriberId = subscriberId;
	}
	
	@DynamoDBAttribute
	public String getTopic() {
		return topic;
	}
	
	public void setTopic(String topic) {
		this.topic = topic;
	}
	
	@DynamoDBAttribute
	public Set<String> getUrlSet() {
		return urlSet;
	}
	
	public void setUrlSet(Set<String> urlSet) {
		this.urlSet = urlSet;
	}
}