package rss.feeds.subscriber.dataprovider;

import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlRootElement;

import org.springframework.context.annotation.Configuration;
import org.springframework.stereotype.Component;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

/*
 * User table: Subscriber table:

UserId
UserName
Address
EmailAddress
Info
ChannelIds
 */
@Component
@Configuration
@XmlRootElement
@DynamoDBTable(tableName = "subscriber")
public class SubscriberObjectMapper {
	
	@DynamoDBHashKey
	String mId;
	String mEmailAddress;
	String mName;
	Set<String> mChannelIds;
	
	public SubscriberObjectMapper() {
		mChannelIds = new HashSet<String>();
	}
	
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	public String getId(){
		return mId;
	}

	public void setId(String id) {
		this.mId = id;
	}
	
	@DynamoDBAttribute
	public String getEmailAddress() {
		return mEmailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.mEmailAddress = emailAddress;
	}
	
	@DynamoDBAttribute
	public String getName() {
		return mName;
	}
	
	public void setName(String name) {
		this.mName = name;
	}
	
	@DynamoDBAttribute
	public Set<String> getChannelIds() {
		return mChannelIds;
	}

	public void setChannels(Set<String> channelIds) {
		mChannelIds.clear();
		mChannelIds.addAll(channelIds);
	}
}